#!/usr/bin/env bash
# SPDX-License-Identifier: Apache-2.0
# Bootstrap a fresh NiXOA system checkout on a NixOS host

set -euo pipefail

usage() {
  cat <<'EOF'
Usage: bootstrap.sh [options]

Options:
  --repo-dir PATH       Checkout directory. Defaults to $HOME/system.
  --repo-url URL        System repository URL.
  --branch NAME         Branch to clone or update. Defaults to beta.
  --hostname NAME       Write hostname into config/overrides.nix.
  --username NAME       Write username into config/overrides.nix.
  --timezone ZONE       Write timezone into config/overrides.nix.
  --state-version VER   Write stateVersion into config/overrides.nix.
  --ssh-key KEY         Add an SSH public key to config/overrides.nix. Repeatable.
  --skip-check          Skip nix flake check.
  --skip-hardware-copy  Do not copy /etc/nixos/hardware-configuration.nix.
  --first-switch        Run apply-config.sh --first-install after setup.
  --help                Show this help text.
EOF
}

nix_quote() {
  printf '"%s"' "$(printf '%s' "$1" | sed 's/\\/\\\\/g; s/"/\\"/g')"
}

repo_url="https://codeberg.org/NiXOA/system.git"
branch="beta"
repo_dir="${HOME:-/root}/system"
skip_check=0
skip_hardware_copy=0
first_switch=0
hostname_arg=""
username_arg=""
timezone_arg=""
state_version_arg=""
declare -a ssh_keys=()

while [ $# -gt 0 ]; do
  case "$1" in
    --repo-dir)
      repo_dir="$2"
      shift 2
      ;;
    --repo-url)
      repo_url="$2"
      shift 2
      ;;
    --branch)
      branch="$2"
      shift 2
      ;;
    --hostname)
      hostname_arg="$2"
      shift 2
      ;;
    --username)
      username_arg="$2"
      shift 2
      ;;
    --timezone)
      timezone_arg="$2"
      shift 2
      ;;
    --state-version)
      state_version_arg="$2"
      shift 2
      ;;
    --ssh-key)
      ssh_keys+=("$2")
      shift 2
      ;;
    --skip-check)
      skip_check=1
      shift
      ;;
    --skip-hardware-copy)
      skip_hardware_copy=1
      shift
      ;;
    --first-switch)
      first_switch=1
      shift
      ;;
    --help)
      usage
      exit 0
      ;;
    *)
      echo "Unknown option: $1" >&2
      usage >&2
      exit 1
      ;;
  esac
done

mkdir -p "$(dirname "$repo_dir")"

if [ -d "$repo_dir/.git" ]; then
  echo "Updating existing checkout in $repo_dir"
  git -C "$repo_dir" fetch origin "$branch"
  git -C "$repo_dir" checkout "$branch"
  git -C "$repo_dir" pull --ff-only origin "$branch"
else
  echo "Cloning $repo_url into $repo_dir"
  git clone --branch "$branch" "$repo_url" "$repo_dir"
fi

if [ "$skip_hardware_copy" -eq 0 ] && [ -f /etc/nixos/hardware-configuration.nix ]; then
  install -m 0644 /etc/nixos/hardware-configuration.nix "$repo_dir/hardware-configuration.nix"
  echo "Copied hardware-configuration.nix"
fi

if [ -n "$hostname_arg" ] || [ -n "$username_arg" ] || [ -n "$timezone_arg" ] || [ -n "$state_version_arg" ] || [ "${#ssh_keys[@]}" -gt 0 ]; then
  overrides_file="$repo_dir/config/overrides.nix"
  {
    echo "# SPDX-License-Identifier: Apache-2.0"
    echo "# Generated by scripts/bootstrap.sh"
    echo "{ ... }:"
    echo "{"
    if [ -n "$hostname_arg" ]; then
      echo "  hostname = $(nix_quote "$hostname_arg");"
    fi
    if [ -n "$username_arg" ]; then
      echo "  username = $(nix_quote "$username_arg");"
    fi
    if [ -n "$timezone_arg" ]; then
      echo "  timezone = $(nix_quote "$timezone_arg");"
    fi
    if [ -n "$state_version_arg" ]; then
      echo "  stateVersion = $(nix_quote "$state_version_arg");"
    fi
    if [ "${#ssh_keys[@]}" -gt 0 ]; then
      echo "  sshKeys = ["
      for ssh_key in "${ssh_keys[@]}"; do
        echo "    $(nix_quote "$ssh_key")"
      done
      echo "  ];"
    fi
    echo "}"
  } > "$overrides_file"
  echo "Wrote $overrides_file"
fi

if [ "$skip_check" -eq 0 ]; then
  echo "Running nix flake check"
  (cd "$repo_dir" && nix flake check --no-write-lock-file)
fi

if [ "$first_switch" -eq 1 ]; then
  switch_host="${hostname_arg:-$(hostname -s 2>/dev/null || printf '%s\n' nixoa)}"
  echo "Running first switch for ${switch_host}"
  "$repo_dir/scripts/apply-config.sh" --hostname "$switch_host" --first-install
fi

echo ""
echo "Bootstrap complete."
echo "Repository: $repo_dir"
echo "Next steps:"
echo "  1. Review overrides in $repo_dir/config/overrides.nix if you generated them."
echo "  2. Run $repo_dir/scripts/show-diff.sh"
echo "  3. Run $repo_dir/scripts/apply-config.sh --hostname ${hostname_arg:-$(hostname -s 2>/dev/null || printf '%s\n' nixoa)}"
